kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - yarn
  - yarn build

- name: deploy
  image: node
  environment:
    SURFER_USERNAME:
      from_secret: SURFER_USERNAME
    SURFER_PASSWORD:
      from_secret: SURFER_PASSWORD
    SURFER_TOKEN:
      from_secret: SURFER_TOKEN
    SURFER_URL:
      from_secret: SURFER_URL
  commands:
  - echo $SURFER_URL
  - echo ${SURFER_URL}
  - npm -g install cloudron-surfer
  - surfer login ${SURFER_URL} --username ${SURFER_USERNAME} --password ${SURFER_PASSWORD}
  - surfer put dist/* /