kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - yarn
  - yarn build

- name: frontend
  image: node
  envoronment:
    SURFER_TOKEN:
      from_secret: SURFER_TOKEN
    SURVER_URL:
      from_secret: SURVER_URL
  commands:
  - npm -g install cloudron-surfer
  - surfer put --token "$SURFER_TOKEN" --server "$SURFER_URL" dist/* /