kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - yarn
  - yarn build

- name: deploy
  image: node
  envoronment:
    SURFER_USERNAME:
      from_secret: SURFER_USERNAME
    SURFER_PASSWORD:
      from_secret: SURFER_PASSWORD
    SURVER_URL:
      from_secret: SURVER_URL
  commands:
  - npm -g install cloudron-surfer
  - surfer login --username $SURFER_USERNAME --password $SURFER_PASSWORD $SURFER_URL
  - surfer put dist/* / --