name: CDK Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v1

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16"
      env:
        AWS_DOMAIN: ${{ secrets.AWS_DOMAIN }}
        AWS_HOSTEDZONEID: ${{ secrets.AWS_HOSTEDZONEID }}
    - run: npm i -g yarn
    - run: yarn
    - run: yarn build
    - run: cd cdk && yarn deploy --parameters domain=$AWS_DOMAIN  --parameters hostedZoneID=$AWS_HOSTEDZONEID
